// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: my.proto

package helloG.messages;

public final class StudentProtos {
    private StudentProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface StudentOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Student)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string id = 1;</code>
         */
        String getId();
        /**
         * <code>string id = 1;</code>
         */
        com.google.protobuf.ByteString
        getIdBytes();

        /**
         * <code>string first_name = 2;</code>
         */
        String getFirstName();
        /**
         * <code>string first_name = 2;</code>
         */
        com.google.protobuf.ByteString
        getFirstNameBytes();

        /**
         * <code>string last_name = 3;</code>
         */
        String getLastName();
        /**
         * <code>string last_name = 3;</code>
         */
        com.google.protobuf.ByteString
        getLastNameBytes();

        /**
         * <code>string email = 4;</code>
         */
        String getEmail();
        /**
         * <code>string email = 4;</code>
         */
        com.google.protobuf.ByteString
        getEmailBytes();

        /**
         * <code>repeated string courses = 5;</code>
         */
        java.util.List<String>
        getCoursesList();
        /**
         * <code>repeated string courses = 5;</code>
         */
        int getCoursesCount();
        /**
         * <code>repeated string courses = 5;</code>
         */
        String getCourses(int index);
        /**
         * <code>repeated string courses = 5;</code>
         */
        com.google.protobuf.ByteString
        getCoursesBytes(int index);

        /**
         * <code>string avatar = 6;</code>
         */
        String getAvatar();
        /**
         * <code>string avatar = 6;</code>
         */
        com.google.protobuf.ByteString
        getAvatarBytes();
    }
    /**
     * Protobuf type {@code Student}
     */
    public  static final class Student extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Student)
            StudentOrBuilder {
        private static final long serialVersionUID = 0L;
        // Use Student.newBuilder() to construct.
        private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private Student() {
            id_ = "";
            firstName_ = "";
            lastName_ = "";
            email_ = "";
            courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            avatar_ = "";
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }
        private Student(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            id_ = s;
                            break;
                        }
                        case 18: {
                            String s = input.readStringRequireUtf8();

                            firstName_ = s;
                            break;
                        }
                        case 26: {
                            String s = input.readStringRequireUtf8();

                            lastName_ = s;
                            break;
                        }
                        case 34: {
                            String s = input.readStringRequireUtf8();

                            email_ = s;
                            break;
                        }
                        case 42: {
                            String s = input.readStringRequireUtf8();
                            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                                courses_ = new com.google.protobuf.LazyStringArrayList();
                                mutable_bitField0_ |= 0x00000010;
                            }
                            courses_.add(s);
                            break;
                        }
                        case 50: {
                            String s = input.readStringRequireUtf8();

                            avatar_ = s;
                            break;
                        }
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                    courses_ = courses_.getUnmodifiableView();
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return helloG.messages.StudentProtos.internal_static_Student_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return helloG.messages.StudentProtos.internal_static_Student_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            helloG.messages.StudentProtos.Student.class, helloG.messages.StudentProtos.Student.Builder.class);
        }

        private int bitField0_;
        public static final int ID_FIELD_NUMBER = 1;
        private volatile Object id_;
        /**
         * <code>string id = 1;</code>
         */
        public String getId() {
            Object ref = id_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                id_ = s;
                return s;
            }
        }
        /**
         * <code>string id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getIdBytes() {
            Object ref = id_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int FIRST_NAME_FIELD_NUMBER = 2;
        private volatile Object firstName_;
        /**
         * <code>string first_name = 2;</code>
         */
        public String getFirstName() {
            Object ref = firstName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                firstName_ = s;
                return s;
            }
        }
        /**
         * <code>string first_name = 2;</code>
         */
        public com.google.protobuf.ByteString
        getFirstNameBytes() {
            Object ref = firstName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                firstName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int LAST_NAME_FIELD_NUMBER = 3;
        private volatile Object lastName_;
        /**
         * <code>string last_name = 3;</code>
         */
        public String getLastName() {
            Object ref = lastName_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                lastName_ = s;
                return s;
            }
        }
        /**
         * <code>string last_name = 3;</code>
         */
        public com.google.protobuf.ByteString
        getLastNameBytes() {
            Object ref = lastName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                lastName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int EMAIL_FIELD_NUMBER = 4;
        private volatile Object email_;
        /**
         * <code>string email = 4;</code>
         */
        public String getEmail() {
            Object ref = email_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                email_ = s;
                return s;
            }
        }
        /**
         * <code>string email = 4;</code>
         */
        public com.google.protobuf.ByteString
        getEmailBytes() {
            Object ref = email_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                email_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int COURSES_FIELD_NUMBER = 5;
        private com.google.protobuf.LazyStringList courses_;
        /**
         * <code>repeated string courses = 5;</code>
         */
        public com.google.protobuf.ProtocolStringList
        getCoursesList() {
            return courses_;
        }
        /**
         * <code>repeated string courses = 5;</code>
         */
        public int getCoursesCount() {
            return courses_.size();
        }
        /**
         * <code>repeated string courses = 5;</code>
         */
        public String getCourses(int index) {
            return courses_.get(index);
        }
        /**
         * <code>repeated string courses = 5;</code>
         */
        public com.google.protobuf.ByteString
        getCoursesBytes(int index) {
            return courses_.getByteString(index);
        }

        public static final int AVATAR_FIELD_NUMBER = 6;
        private volatile Object avatar_;
        /**
         * <code>string avatar = 6;</code>
         */
        public String getAvatar() {
            Object ref = avatar_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                avatar_ = s;
                return s;
            }
        }
        /**
         * <code>string avatar = 6;</code>
         */
        public com.google.protobuf.ByteString
        getAvatarBytes() {
            Object ref = avatar_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                avatar_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;
        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
            }
            if (!getFirstNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
            }
            if (!getLastNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
            }
            if (!getEmailBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
            }
            for (int i = 0; i < courses_.size(); i++) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, courses_.getRaw(i));
            }
            if (!getAvatarBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, avatar_);
            }
            unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
            }
            if (!getFirstNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
            }
            if (!getLastNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
            }
            if (!getEmailBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
            }
            {
                int dataSize = 0;
                for (int i = 0; i < courses_.size(); i++) {
                    dataSize += computeStringSizeNoTag(courses_.getRaw(i));
                }
                size += dataSize;
                size += 1 * getCoursesList().size();
            }
            if (!getAvatarBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, avatar_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof helloG.messages.StudentProtos.Student)) {
                return super.equals(obj);
            }
            helloG.messages.StudentProtos.Student other = (helloG.messages.StudentProtos.Student) obj;

            boolean result = true;
            result = result && getId()
                    .equals(other.getId());
            result = result && getFirstName()
                    .equals(other.getFirstName());
            result = result && getLastName()
                    .equals(other.getLastName());
            result = result && getEmail()
                    .equals(other.getEmail());
            result = result && getCoursesList()
                    .equals(other.getCoursesList());
            result = result && getAvatar()
                    .equals(other.getAvatar());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + getId().hashCode();
            hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getFirstName().hashCode();
            hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getLastName().hashCode();
            hash = (37 * hash) + EMAIL_FIELD_NUMBER;
            hash = (53 * hash) + getEmail().hashCode();
            if (getCoursesCount() > 0) {
                hash = (37 * hash) + COURSES_FIELD_NUMBER;
                hash = (53 * hash) + getCoursesList().hashCode();
            }
            hash = (37 * hash) + AVATAR_FIELD_NUMBER;
            hash = (53 * hash) + getAvatar().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static helloG.messages.StudentProtos.Student parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static helloG.messages.StudentProtos.Student parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static helloG.messages.StudentProtos.Student parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static helloG.messages.StudentProtos.Student parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(helloG.messages.StudentProtos.Student prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code Student}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Student)
                helloG.messages.StudentProtos.StudentOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return helloG.messages.StudentProtos.internal_static_Student_descriptor;
            }

            @Override
            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return helloG.messages.StudentProtos.internal_static_Student_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                helloG.messages.StudentProtos.Student.class, helloG.messages.StudentProtos.Student.Builder.class);
            }

            // Construct using helloG.messages.StudentProtos.Student.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            @Override
            public Builder clear() {
                super.clear();
                id_ = "";

                firstName_ = "";

                lastName_ = "";

                email_ = "";

                courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);
                avatar_ = "";

                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return helloG.messages.StudentProtos.internal_static_Student_descriptor;
            }

            @Override
            public helloG.messages.StudentProtos.Student getDefaultInstanceForType() {
                return helloG.messages.StudentProtos.Student.getDefaultInstance();
            }

            @Override
            public helloG.messages.StudentProtos.Student build() {
                helloG.messages.StudentProtos.Student result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public helloG.messages.StudentProtos.Student buildPartial() {
                helloG.messages.StudentProtos.Student result = new helloG.messages.StudentProtos.Student(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                result.id_ = id_;
                result.firstName_ = firstName_;
                result.lastName_ = lastName_;
                result.email_ = email_;
                if (((bitField0_ & 0x00000010) == 0x00000010)) {
                    courses_ = courses_.getUnmodifiableView();
                    bitField0_ = (bitField0_ & ~0x00000010);
                }
                result.courses_ = courses_;
                result.avatar_ = avatar_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @Override
            public Builder clone() {
                return (Builder) super.clone();
            }
            @Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            @Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            @Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            @Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            @Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof helloG.messages.StudentProtos.Student) {
                    return mergeFrom((helloG.messages.StudentProtos.Student)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(helloG.messages.StudentProtos.Student other) {
                if (other == helloG.messages.StudentProtos.Student.getDefaultInstance()) return this;
                if (!other.getId().isEmpty()) {
                    id_ = other.id_;
                    onChanged();
                }
                if (!other.getFirstName().isEmpty()) {
                    firstName_ = other.firstName_;
                    onChanged();
                }
                if (!other.getLastName().isEmpty()) {
                    lastName_ = other.lastName_;
                    onChanged();
                }
                if (!other.getEmail().isEmpty()) {
                    email_ = other.email_;
                    onChanged();
                }
                if (!other.courses_.isEmpty()) {
                    if (courses_.isEmpty()) {
                        courses_ = other.courses_;
                        bitField0_ = (bitField0_ & ~0x00000010);
                    } else {
                        ensureCoursesIsMutable();
                        courses_.addAll(other.courses_);
                    }
                    onChanged();
                }
                if (!other.getAvatar().isEmpty()) {
                    avatar_ = other.avatar_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                helloG.messages.StudentProtos.Student parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (helloG.messages.StudentProtos.Student) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            private int bitField0_;

            private Object id_ = "";
            /**
             * <code>string id = 1;</code>
             */
            public String getId() {
                Object ref = id_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    id_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getIdBytes() {
                Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string id = 1;</code>
             */
            public Builder setId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                id_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string id = 1;</code>
             */
            public Builder clearId() {

                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }
            /**
             * <code>string id = 1;</code>
             */
            public Builder setIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                id_ = value;
                onChanged();
                return this;
            }

            private Object firstName_ = "";
            /**
             * <code>string first_name = 2;</code>
             */
            public String getFirstName() {
                Object ref = firstName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    firstName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string first_name = 2;</code>
             */
            public com.google.protobuf.ByteString
            getFirstNameBytes() {
                Object ref = firstName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    firstName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string first_name = 2;</code>
             */
            public Builder setFirstName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                firstName_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string first_name = 2;</code>
             */
            public Builder clearFirstName() {

                firstName_ = getDefaultInstance().getFirstName();
                onChanged();
                return this;
            }
            /**
             * <code>string first_name = 2;</code>
             */
            public Builder setFirstNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                firstName_ = value;
                onChanged();
                return this;
            }

            private Object lastName_ = "";
            /**
             * <code>string last_name = 3;</code>
             */
            public String getLastName() {
                Object ref = lastName_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    lastName_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string last_name = 3;</code>
             */
            public com.google.protobuf.ByteString
            getLastNameBytes() {
                Object ref = lastName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    lastName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string last_name = 3;</code>
             */
            public Builder setLastName(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                lastName_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string last_name = 3;</code>
             */
            public Builder clearLastName() {

                lastName_ = getDefaultInstance().getLastName();
                onChanged();
                return this;
            }
            /**
             * <code>string last_name = 3;</code>
             */
            public Builder setLastNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                lastName_ = value;
                onChanged();
                return this;
            }

            private Object email_ = "";
            /**
             * <code>string email = 4;</code>
             */
            public String getEmail() {
                Object ref = email_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    email_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string email = 4;</code>
             */
            public com.google.protobuf.ByteString
            getEmailBytes() {
                Object ref = email_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    email_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string email = 4;</code>
             */
            public Builder setEmail(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                email_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string email = 4;</code>
             */
            public Builder clearEmail() {

                email_ = getDefaultInstance().getEmail();
                onChanged();
                return this;
            }
            /**
             * <code>string email = 4;</code>
             */
            public Builder setEmailBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                email_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.LazyStringList courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
            private void ensureCoursesIsMutable() {
                if (!((bitField0_ & 0x00000010) == 0x00000010)) {
                    courses_ = new com.google.protobuf.LazyStringArrayList(courses_);
                    bitField0_ |= 0x00000010;
                }
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public com.google.protobuf.ProtocolStringList
            getCoursesList() {
                return courses_.getUnmodifiableView();
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public int getCoursesCount() {
                return courses_.size();
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public String getCourses(int index) {
                return courses_.get(index);
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public com.google.protobuf.ByteString
            getCoursesBytes(int index) {
                return courses_.getByteString(index);
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public Builder setCourses(
                    int index, String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureCoursesIsMutable();
                courses_.set(index, value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public Builder addCourses(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureCoursesIsMutable();
                courses_.add(value);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public Builder addAllCourses(
                    Iterable<String> values) {
                ensureCoursesIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(
                        values, courses_);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public Builder clearCourses() {
                courses_ = com.google.protobuf.LazyStringArrayList.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);
                onChanged();
                return this;
            }
            /**
             * <code>repeated string courses = 5;</code>
             */
            public Builder addCoursesBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                ensureCoursesIsMutable();
                courses_.add(value);
                onChanged();
                return this;
            }

            private Object avatar_ = "";
            /**
             * <code>string avatar = 6;</code>
             */
            public String getAvatar() {
                Object ref = avatar_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    avatar_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            /**
             * <code>string avatar = 6;</code>
             */
            public com.google.protobuf.ByteString
            getAvatarBytes() {
                Object ref = avatar_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    avatar_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }
            /**
             * <code>string avatar = 6;</code>
             */
            public Builder setAvatar(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                avatar_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>string avatar = 6;</code>
             */
            public Builder clearAvatar() {

                avatar_ = getDefaultInstance().getAvatar();
                onChanged();
                return this;
            }
            /**
             * <code>string avatar = 6;</code>
             */
            public Builder setAvatarBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                avatar_ = value;
                onChanged();
                return this;
            }
            @Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            @Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Student)
        }

        // @@protoc_insertion_point(class_scope:Student)
        private static final helloG.messages.StudentProtos.Student DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new helloG.messages.StudentProtos.Student();
        }

        public static helloG.messages.StudentProtos.Student getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Student>
                PARSER = new com.google.protobuf.AbstractParser<Student>() {
            @Override
            public Student parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Student(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Student> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Student> getParserForType() {
            return PARSER;
        }

        @Override
        public helloG.messages.StudentProtos.Student getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Student_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Student_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        String[] descriptorData = {
                "\n\010my.proto\"l\n\007Student\022\n\n\002id\030\001 \001(\t\022\022\n\nfir" +
                        "st_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\r\n\005emai" +
                        "l\030\004 \001(\t\022\017\n\007courses\030\005 \003(\t\022\016\n\006avatar\030\006 \001(\t" +
                        "B \n\017helloG.messagesB\rStudentProtosb\006prot" +
                        "o3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_Student_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Student_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Student_descriptor,
                new String[] { "Id", "FirstName", "LastName", "Email", "Courses", "Avatar", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
